### ISSUE TITLE
NC14.0.1 & survey_client 1.2.0: "Deprecated file found - please use repair steps"

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/survey_client#82]
`occ app:check-code survey_client`

```
Deprecated file found: /var/www/html/apps/survey_client/appinfo/update.php - please use repair steps
App is compliant - awesome job!
```

What does this mean: "please use repair steps"?
Thank you!

**Comment by nickvergessen** [comment]
Thanks for opening the remind issues in all the apps.

The `occ app:check-code` command is directed to developers. In this case the app is using an old way to run code while the app is updated.
This is not good, but also not bad yet, because it is still supported. It just might be removed in the future. The fix for the developer is to migrate the app to the new technology (Repair steps).

**Comment by nickvergessen** [comment]
Gone by now
